import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import 'primeicons/primeicons.css';
import { PrimeReactProvider } from 'primereact/api';
import Tailwind from 'primereact/passthrough/tailwind';
// import ThemeSwitcher from './components/themeSwitcher';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <PrimeReactProvider value={{ unstyled: false, pt: Tailwind }}>
        {children}
      </PrimeReactProvider>
      </body>
    </html>
  );
}
